/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    EpCaretBottom: typeof import('~icons/ep/caret-bottom')['default']
    EpCloseBold: typeof import('~icons/ep/close-bold')['default']
    EpRefreshLeft: typeof import('~icons/ep/refresh-left')['default']
    EpRight: typeof import('~icons/ep/right')['default']
    KsDialog: typeof import('./../src/components/zs-dialog/ks-dialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZsAuthRedirect: typeof import('./../src/components/zs-auth-redirect/zs-auth-redirect.vue')['default']
    ZsBreadcrumb: typeof import('./../src/components/zs-breadcrumb/zs-breadcrumb.vue')['default']
    ZsEmpty: typeof import('./../src/components/zs-empty/zs-empty.vue')['default']
    ZsFormLayout: typeof import('./../src/components/zs-form-layout/zs-form-layout.vue')['default']
    ZsHeaderUser: typeof import('./../src/components/zs-header-user/zs-header-user.vue')['default']
    ZsLayout: typeof import('./../src/components/zs-layout/zs-layout.vue')['default']
    ZsMenu: typeof import('./../src/components/zs-menu/zs-menu.vue')['default']
    ZsPagination: typeof import('./../src/components/zs-pagination/zs-pagination.vue')['default']
    ZsScrollIntermittent: typeof import('./../src/components/zs-scroll-intermittent/zs-scroll-intermittent.vue')['default']
    ZsSliderVerify: typeof import('./../src/components/zs-slider-verify/zs-slider-verify.vue')['default']
    ZsSplitContainer: typeof import('./../src/components/zs-split-container/zs-split-container.vue')['default']
    ZsTable: typeof import('./../src/components/zs-table/zs-table.vue')['default']
    ZsTitle: typeof import('./../src/components/zs-title/zs-title.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
